### ISSUE TITLE
Does clm work in this code? 

### ISSUE THREAD

**Issue by aiscientist** [andi611/Mockingjay-Speech-Representation#10]
Hi, I have a question about CLM approaches.

It seems like a code below requires text_only options, but data_loader has no text_only options.

`self.train_set = get_Dataloader('text',text_only=True,**data_config)
`
https://github.com/andi611/Mockingjay-Speech-Representation/blob/05f0315125f4201d9028f807468b4915453a6f74/asr/clm.py#L39

I am just wondering this logic is implemented or not in the current stages.

**Comment by andi611** [comment]
Hi, yes it is not yet implemented!
However, we will soon update the code for ASR.
