### ISSUE TITLE
Where can I get the mosei_no_semi.csv??

### ISSUE THREAD

**Issue by jaeyeonkim99** [andi611/Mockingjay-Speech-Representation#2]
Hello, I'm a student in Seoul National University, and I want to reproduce your work on sentiment analysis. However, after I downloaded the MOSEI dataset and tried to preprocess it using your code, I found out that I cannot run your preprocess_mosei/segment_mosei.py due to the lack of "mosei_no_semi.csv". Where can I find the file "mosei_no_semi.csv"? I cannot find it on the dataset itself.

Thank you!

**Comment by JakobHavtorn** [comment]
Hi @jaeyeonkim99, did you ever find the `mosei_no_semi.csv` file? I am having the same issues and was not able to find it in this repo nor in the `CMU_MOSEI.zip` file downloaded from http://immortal.multicomp.cs.cmu.edu/raw_datasets/CMU_MOSEI.zip.
