### ISSUE TITLE
Is there any instructions how to pre-train the model?

### ISSUE THREAD

**Issue by aiscientist** [andi611/Mockingjay-Speech-Representation#4]
Hi, I would like to know is there any guide for how to preprocessing or where to start.

I can see how to preprocess the downstream tasks.

Thanks!

**Comment by andi611** [comment]
Hi!

It is all written in [README.md](https://github.com/andi611/Mockingjay-Speech-Representation/blob/master/README.md). To be specific, the instructions are listed [here](https://github.com/andi611/Mockingjay-Speech-Representation#instructions).

Thank you for the question.
